---
abstract: 'faster implementation of HTTP::Headers'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Headers-Fast
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  HTTP::Headers::Fast:
    file: lib/HTTP/Headers/Fast.pm
    version: 0.15
requires:
  HTTP::Date: 0
  perl: 5.00800
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
